on:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build plugin
      run: xmake build -y linux
    - name: Pack plugin
      run: xmake pack
    - name: Upload plugin as artifact
      uses: actions/upload-artifact@v4
      with:
        name: result-artifact
        path: build/xpack/audioplayer/audioplayer.zip
